default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ghanban_development

test:
  <<: *default
  database: ghanban_test

production:
  <<: *default
  database: ghanban_production
  username: ghanban
  url: <%= ENV['DATABASE_URL'] %>
