development:
  secret_key_base: <%= ENV['DEV_SECRET_KEY_BASE'] %>
  omniauth_provider_key: <%= ENV["DEV_OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["DEV_OMNIAUTH_PROVIDER_KEY"] %>

test:
  secret_key_base: <%= ENV['TST_SECRET_KEY_BASE'] %>

production:
  omniauth_provider_key: <%= ENV["PRD_OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["PRD_OMNIAUTH_PROVIDER_SECRET"] %>
  secret_key_base: <%= ENV['PRD_SECRET_KEY_BASE'] %>
